path:
  ckpt_path: "./output/ckpt/ESD_en"
  log_path: "./output/log/ESD_en"
  result_path: "./output/result/ESD_en"
optimizer:
  batch_size: 64
  betas: [0.5, 0.9]
  eps: 0.000000001
  weight_decay: 0.0001
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 2000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 30000
  log_step: 100
  synth_step: 1000
  val_step: 2000
  save_step: 1000
